name: Run Command for Affected Folders

on:
  push:
    branches:
      - main

jobs:
  run-for-affected-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List modified files
        run: |
          git fetch origin ${{ github.event.before }} --depth=1
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt

      - name: Extract top-level folders
        id: extract_folders
        run: |
          awk -F/ '{print $1}' modified_files.txt | sort | uniq > folders.txt

      - name: Run command for each folder
        run: |
          while read folder; do
            case $folder in
            [^.]*)
              echo "Triggering scan workflow for $folder"
              gh workflow run scan-folder.yaml -f folder=$folder
              ;;
            *)
              echo "Not triggering scan workflow for $folder"
              ;;
            esac
          done < folders.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
