name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      folder:
        required: true
        type: string

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: echo Folder to scan is ${{ inputs.folder }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Scan code in Checkmarx One
        uses: james-bostock-cx/ast-github-action@68ab7b00cc043f8f140eb6d66df88b3bfe0cad2f
        with:
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_tenant: ${{ secrets.CX_TENANT_NAME }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          src: ${{ inputs.folder }}
