name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      folder:
        required: true
        type: string

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Scan code in Checkmarx One
        uses: james-bostock-cx/ast-github-action@857293df6b79bd4b1894577ec07540bd93d2fe16
        with:
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          src: ${{ inputs.folder }}
